// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core/v1/core.proto

package corev1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // Unique identifier for the service
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // Name of the service
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`               // Description of the service
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Creation timestamp in Unix format
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Last update timestamp in Unix format
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`    // Indicates if the service is active
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_core_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Service) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Service) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Service) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServicesRequest) Reset() {
	*x = GetServicesRequest{}
	mi := &file_core_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServicesRequest) ProtoMessage() {}

func (x *GetServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServicesRequest.ProtoReflect.Descriptor instead.
func (*GetServicesRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{1}
}

type GetServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"` // List of services
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServicesResponse) Reset() {
	*x = GetServicesResponse{}
	mi := &file_core_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServicesResponse) ProtoMessage() {}

func (x *GetServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServicesResponse.ProtoReflect.Descriptor instead.
func (*GetServicesResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *GetServicesResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type GetServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique identifier for the service to retrieve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_core_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *GetServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3,oneof" json:"service,omitempty"` // The requested service details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceResponse) Reset() {
	*x = GetServiceResponse{}
	mi := &file_core_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceResponse) ProtoMessage() {}

func (x *GetServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceResponse.ProtoReflect.Descriptor instead.
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *GetServiceResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type GetIsActiveServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique identifier for the service to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIsActiveServiceRequest) Reset() {
	*x = GetIsActiveServiceRequest{}
	mi := &file_core_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIsActiveServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIsActiveServiceRequest) ProtoMessage() {}

func (x *GetIsActiveServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIsActiveServiceRequest.ProtoReflect.Descriptor instead.
func (*GetIsActiveServiceRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *GetIsActiveServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetIsActiveServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"` // Indicates if the service is active
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIsActiveServiceResponse) Reset() {
	*x = GetIsActiveServiceResponse{}
	mi := &file_core_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIsActiveServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIsActiveServiceResponse) ProtoMessage() {}

func (x *GetIsActiveServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIsActiveServiceResponse.ProtoReflect.Descriptor instead.
func (*GetIsActiveServiceResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{6}
}

func (x *GetIsActiveServiceResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetIsAvailableServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique identifier for the service to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIsAvailableServiceRequest) Reset() {
	*x = GetIsAvailableServiceRequest{}
	mi := &file_core_v1_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIsAvailableServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIsAvailableServiceRequest) ProtoMessage() {}

func (x *GetIsAvailableServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIsAvailableServiceRequest.ProtoReflect.Descriptor instead.
func (*GetIsAvailableServiceRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{7}
}

func (x *GetIsAvailableServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetIsAvailableServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"` // Indicates if the service is available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIsAvailableServiceResponse) Reset() {
	*x = GetIsAvailableServiceResponse{}
	mi := &file_core_v1_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIsAvailableServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIsAvailableServiceResponse) ProtoMessage() {}

func (x *GetIsAvailableServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIsAvailableServiceResponse.ProtoReflect.Descriptor instead.
func (*GetIsAvailableServiceResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{8}
}

func (x *GetIsAvailableServiceResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

var File_core_v1_core_proto protoreflect.FileDescriptor

const file_core_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x12core/v1/core.proto\x12\acore.v1\x1a#third_party/validate/validate.proto\"\xcf\x01\n" +
	"\aService\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12&\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tcreatedAt\x12&\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tupdatedAt\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"\x14\n" +
	"\x12GetServicesRequest\"C\n" +
	"\x13GetServicesResponse\x12,\n" +
	"\bservices\x18\x01 \x03(\v2\x10.core.v1.ServiceR\bservices\"-\n" +
	"\x11GetServiceRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\"Q\n" +
	"\x12GetServiceResponse\x12/\n" +
	"\aservice\x18\x01 \x01(\v2\x10.core.v1.ServiceH\x00R\aservice\x88\x01\x01B\n" +
	"\n" +
	"\b_service\"5\n" +
	"\x19GetIsActiveServiceRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\"9\n" +
	"\x1aGetIsActiveServiceResponse\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\"8\n" +
	"\x1cGetIsAvailableServiceRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\"B\n" +
	"\x1dGetIsAvailableServiceResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable2\xdf\x02\n" +
	"\vCoreService\x12H\n" +
	"\vGetServices\x12\x1b.core.v1.GetServicesRequest\x1a\x1c.core.v1.GetServicesResponse\x12E\n" +
	"\n" +
	"GetService\x12\x1a.core.v1.GetServiceRequest\x1a\x1b.core.v1.GetServiceResponse\x12Z\n" +
	"\x0fIsActiveService\x12\".core.v1.GetIsActiveServiceRequest\x1a#.core.v1.GetIsActiveServiceResponse\x12c\n" +
	"\x12IsAvailableService\x12%.core.v1.GetIsAvailableServiceRequest\x1a&.core.v1.GetIsAvailableServiceResponseB;Z9github.com/mandacode-com/seregeti-proto/go/core/v1;corev1b\x06proto3"

var (
	file_core_v1_core_proto_rawDescOnce sync.Once
	file_core_v1_core_proto_rawDescData []byte
)

func file_core_v1_core_proto_rawDescGZIP() []byte {
	file_core_v1_core_proto_rawDescOnce.Do(func() {
		file_core_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_core_proto_rawDesc), len(file_core_v1_core_proto_rawDesc)))
	})
	return file_core_v1_core_proto_rawDescData
}

var file_core_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_core_v1_core_proto_goTypes = []any{
	(*Service)(nil),                       // 0: core.v1.Service
	(*GetServicesRequest)(nil),            // 1: core.v1.GetServicesRequest
	(*GetServicesResponse)(nil),           // 2: core.v1.GetServicesResponse
	(*GetServiceRequest)(nil),             // 3: core.v1.GetServiceRequest
	(*GetServiceResponse)(nil),            // 4: core.v1.GetServiceResponse
	(*GetIsActiveServiceRequest)(nil),     // 5: core.v1.GetIsActiveServiceRequest
	(*GetIsActiveServiceResponse)(nil),    // 6: core.v1.GetIsActiveServiceResponse
	(*GetIsAvailableServiceRequest)(nil),  // 7: core.v1.GetIsAvailableServiceRequest
	(*GetIsAvailableServiceResponse)(nil), // 8: core.v1.GetIsAvailableServiceResponse
}
var file_core_v1_core_proto_depIdxs = []int32{
	0, // 0: core.v1.GetServicesResponse.services:type_name -> core.v1.Service
	0, // 1: core.v1.GetServiceResponse.service:type_name -> core.v1.Service
	1, // 2: core.v1.CoreService.GetServices:input_type -> core.v1.GetServicesRequest
	3, // 3: core.v1.CoreService.GetService:input_type -> core.v1.GetServiceRequest
	5, // 4: core.v1.CoreService.IsActiveService:input_type -> core.v1.GetIsActiveServiceRequest
	7, // 5: core.v1.CoreService.IsAvailableService:input_type -> core.v1.GetIsAvailableServiceRequest
	2, // 6: core.v1.CoreService.GetServices:output_type -> core.v1.GetServicesResponse
	4, // 7: core.v1.CoreService.GetService:output_type -> core.v1.GetServiceResponse
	6, // 8: core.v1.CoreService.IsActiveService:output_type -> core.v1.GetIsActiveServiceResponse
	8, // 9: core.v1.CoreService.IsAvailableService:output_type -> core.v1.GetIsAvailableServiceResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_v1_core_proto_init() }
func file_core_v1_core_proto_init() {
	if File_core_v1_core_proto != nil {
		return
	}
	file_core_v1_core_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_core_proto_rawDesc), len(file_core_v1_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_core_proto_goTypes,
		DependencyIndexes: file_core_v1_core_proto_depIdxs,
		MessageInfos:      file_core_v1_core_proto_msgTypes,
	}.Build()
	File_core_v1_core_proto = out.File
	file_core_v1_core_proto_goTypes = nil
	file_core_v1_core_proto_depIdxs = nil
}
