// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: client/v1/client.proto

package clientv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// domain types
type ClientStatus int32

const (
	ClientStatus_CLIENT_STATUS_UNSPECIFIED ClientStatus = 0 // Default value, should not be used
	ClientStatus_CLIENT_STATUS_ACTIVE      ClientStatus = 1 // Client is active
	ClientStatus_CLIENT_STATUS_INACTIVE    ClientStatus = 2 // Client is inactive
)

// Enum value maps for ClientStatus.
var (
	ClientStatus_name = map[int32]string{
		0: "CLIENT_STATUS_UNSPECIFIED",
		1: "CLIENT_STATUS_ACTIVE",
		2: "CLIENT_STATUS_INACTIVE",
	}
	ClientStatus_value = map[string]int32{
		"CLIENT_STATUS_UNSPECIFIED": 0,
		"CLIENT_STATUS_ACTIVE":      1,
		"CLIENT_STATUS_INACTIVE":    2,
	}
)

func (x ClientStatus) Enum() *ClientStatus {
	p := new(ClientStatus)
	*p = x
	return p
}

func (x ClientStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v1_client_proto_enumTypes[0].Descriptor()
}

func (ClientStatus) Type() protoreflect.EnumType {
	return &file_client_v1_client_proto_enumTypes[0]
}

func (x ClientStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientStatus.Descriptor instead.
func (ClientStatus) EnumDescriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{0}
}

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique identifier for the client
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientName    string                 `protobuf:"bytes,4,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`       // Name of the client
	RedirectUris  []string               `protobuf:"bytes,5,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"` // List of redirect URIs for the client
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Status        ClientStatus           `protobuf:"varint,8,opt,name=status,proto3,enum=client.v1.ClientStatus" json:"status,omitempty"` // Status of the client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_client_v1_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Client) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Client) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Client) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Client) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

func (x *Client) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Client) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Client) GetStatus() ClientStatus {
	if x != nil {
		return x.Status
	}
	return ClientStatus_CLIENT_STATUS_UNSPECIFIED
}

type CreateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`          // Unique identifier for the service
	ClientName    string                 `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`       // Name of the client
	RedirectUris  []string               `protobuf:"bytes,3,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"` // List of redirect URIs for the client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	mi := &file_client_v1_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{1}
}

func (x *CreateClientRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CreateClientRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *CreateClientRequest) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

type CreateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *Client                `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`                                 // Created client
	ClientSecret  []byte                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"` // Secret for the client, using bytes for flexibility
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientResponse) Reset() {
	*x = CreateClientResponse{}
	mi := &file_client_v1_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientResponse) ProtoMessage() {}

func (x *CreateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientResponse.ProtoReflect.Descriptor instead.
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{2}
}

func (x *CreateClientResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *CreateClientResponse) GetClientSecret() []byte {
	if x != nil {
		return x.ClientSecret
	}
	return nil
}

type ListClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // Unique identifier for the service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsRequest) Reset() {
	*x = ListClientsRequest{}
	mi := &file_client_v1_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsRequest) ProtoMessage() {}

func (x *ListClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsRequest.ProtoReflect.Descriptor instead.
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{3}
}

func (x *ListClientsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type ListClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*Client              `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"` // List of clients
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
	mi := &file_client_v1_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsResponse.ProtoReflect.Descriptor instead.
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{4}
}

func (x *ListClientsResponse) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

type DeleteClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique identifier for the client to be deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientRequest) Reset() {
	*x = DeleteClientRequest{}
	mi := &file_client_v1_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientRequest) ProtoMessage() {}

func (x *DeleteClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Indicates if the deletion was successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientResponse) Reset() {
	*x = DeleteClientResponse{}
	mi := &file_client_v1_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientResponse) ProtoMessage() {}

func (x *DeleteClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientResponse.ProtoReflect.Descriptor instead.
func (*DeleteClientResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RotateClientSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique identifier for the client to rotate secret
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateClientSecretRequest) Reset() {
	*x = RotateClientSecretRequest{}
	mi := &file_client_v1_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateClientSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateClientSecretRequest) ProtoMessage() {}

func (x *RotateClientSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateClientSecretRequest.ProtoReflect.Descriptor instead.
func (*RotateClientSecretRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{7}
}

func (x *RotateClientSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RotateClientSecretResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NewClientSecret []byte                 `protobuf:"bytes,1,opt,name=new_client_secret,json=newClientSecret,proto3" json:"new_client_secret,omitempty"` // New secret for the client, using bytes for flexibility
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RotateClientSecretResponse) Reset() {
	*x = RotateClientSecretResponse{}
	mi := &file_client_v1_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateClientSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateClientSecretResponse) ProtoMessage() {}

func (x *RotateClientSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateClientSecretResponse.ProtoReflect.Descriptor instead.
func (*RotateClientSecretResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{8}
}

func (x *RotateClientSecretResponse) GetNewClientSecret() []byte {
	if x != nil {
		return x.NewClientSecret
	}
	return nil
}

type UpdateRedirectUrisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // Unique identifier for the client to update redirect URIs
	RedirectUris  []string               `protobuf:"bytes,2,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"` // Updated list of redirect URIs for the client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRedirectUrisRequest) Reset() {
	*x = UpdateRedirectUrisRequest{}
	mi := &file_client_v1_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRedirectUrisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRedirectUrisRequest) ProtoMessage() {}

func (x *UpdateRedirectUrisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRedirectUrisRequest.ProtoReflect.Descriptor instead.
func (*UpdateRedirectUrisRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRedirectUrisRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRedirectUrisRequest) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

type UpdateRedirectUrisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *Client                `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"` // Client with updated redirect URIs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRedirectUrisResponse) Reset() {
	*x = UpdateRedirectUrisResponse{}
	mi := &file_client_v1_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRedirectUrisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRedirectUrisResponse) ProtoMessage() {}

func (x *UpdateRedirectUrisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRedirectUrisResponse.ProtoReflect.Descriptor instead.
func (*UpdateRedirectUrisResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRedirectUrisResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type VerifyClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`          // Unique identifier for the service
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`             // Unique identifier for the client
	ClientSecret  []byte                 `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"` // Secret for the client, using bytes for flexibility
	RedirectUri   string                 `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`    // Redirect URI for the client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyClientRequest) Reset() {
	*x = VerifyClientRequest{}
	mi := &file_client_v1_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyClientRequest) ProtoMessage() {}

func (x *VerifyClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyClientRequest.ProtoReflect.Descriptor instead.
func (*VerifyClientRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyClientRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *VerifyClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *VerifyClientRequest) GetClientSecret() []byte {
	if x != nil {
		return x.ClientSecret
	}
	return nil
}

func (x *VerifyClientRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type VerifyClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"` // Indicates if the client was successfully verified
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyClientResponse) Reset() {
	*x = VerifyClientResponse{}
	mi := &file_client_v1_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyClientResponse) ProtoMessage() {}

func (x *VerifyClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyClientResponse.ProtoReflect.Descriptor instead.
func (*VerifyClientResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_client_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyClientResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

var File_client_v1_client_proto protoreflect.FileDescriptor

const file_client_v1_client_proto_rawDesc = "" +
	"\n" +
	"\x16client/v1/client.proto\x12\tclient.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#third_party/validate/validate.proto\"\xfa\x02\n" +
	"\x06Client\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x12'\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\tserviceId\x12$\n" +
	"\tclient_id\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bclientId\x12(\n" +
	"\vclient_name\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"clientName\x126\n" +
	"\rredirect_uris\x18\x05 \x03(\tB\x11\xfaB\x0e\x92\x01\v\b\x01\x18\x01\"\x05r\x03\x88\x01\x01R\fredirectUris\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12/\n" +
	"\x06status\x18\b \x01(\x0e2\x17.client.v1.ClientStatusR\x06status\"\xa0\x01\n" +
	"\x13CreateClientRequest\x12'\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\tserviceId\x12(\n" +
	"\vclient_name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"clientName\x126\n" +
	"\rredirect_uris\x18\x03 \x03(\tB\x11\xfaB\x0e\x92\x01\v\b\x01\x18\x01\"\x05r\x03\x88\x01\x01R\fredirectUris\"o\n" +
	"\x14CreateClientResponse\x12)\n" +
	"\x06client\x18\x01 \x01(\v2\x11.client.v1.ClientR\x06client\x12,\n" +
	"\rclient_secret\x18\x02 \x01(\fB\a\xfaB\x04z\x02\x10\x01R\fclientSecret\"=\n" +
	"\x12ListClientsRequest\x12'\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\tserviceId\"B\n" +
	"\x13ListClientsResponse\x12+\n" +
	"\aclients\x18\x01 \x03(\v2\x11.client.v1.ClientR\aclients\"/\n" +
	"\x13DeleteClientRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\"0\n" +
	"\x14DeleteClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x19RotateClientSecretRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\"Q\n" +
	"\x1aRotateClientSecretResponse\x123\n" +
	"\x11new_client_secret\x18\x01 \x01(\fB\a\xfaB\x04z\x02\x10\x01R\x0fnewClientSecret\"m\n" +
	"\x19UpdateRedirectUrisRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x126\n" +
	"\rredirect_uris\x18\x02 \x03(\tB\x11\xfaB\x0e\x92\x01\v\b\x01\x18\x01\"\x05r\x03\x88\x01\x01R\fredirectUris\"G\n" +
	"\x1aUpdateRedirectUrisResponse\x12)\n" +
	"\x06client\x18\x01 \x01(\v2\x11.client.v1.ClientR\x06client\"\xbf\x01\n" +
	"\x13VerifyClientRequest\x12'\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\tserviceId\x12$\n" +
	"\tclient_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bclientId\x12,\n" +
	"\rclient_secret\x18\x03 \x01(\fB\a\xfaB\x04z\x02\x10\x01R\fclientSecret\x12+\n" +
	"\fredirect_uri\x18\x04 \x01(\tB\b\xfaB\x05r\x03\x88\x01\x01R\vredirectUri\"2\n" +
	"\x14VerifyClientResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified*c\n" +
	"\fClientStatus\x12\x1d\n" +
	"\x19CLIENT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CLIENT_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16CLIENT_STATUS_INACTIVE\x10\x022\x96\x04\n" +
	"\rClientService\x12O\n" +
	"\fCreateClient\x12\x1e.client.v1.CreateClientRequest\x1a\x1f.client.v1.CreateClientResponse\x12L\n" +
	"\vListClients\x12\x1d.client.v1.ListClientsRequest\x1a\x1e.client.v1.ListClientsResponse\x12O\n" +
	"\fDeleteClient\x12\x1e.client.v1.DeleteClientRequest\x1a\x1f.client.v1.DeleteClientResponse\x12a\n" +
	"\x12RotateClientSecret\x12$.client.v1.RotateClientSecretRequest\x1a%.client.v1.RotateClientSecretResponse\x12a\n" +
	"\x12UpdateRedirectUris\x12$.client.v1.UpdateRedirectUrisRequest\x1a%.client.v1.UpdateRedirectUrisResponse\x12O\n" +
	"\fVerifyClient\x12\x1e.client.v1.VerifyClientRequest\x1a\x1f.client.v1.VerifyClientResponseB?Z=github.com/mandacode-com/seregeti-proto/go/client/v1;clientv1b\x06proto3"

var (
	file_client_v1_client_proto_rawDescOnce sync.Once
	file_client_v1_client_proto_rawDescData []byte
)

func file_client_v1_client_proto_rawDescGZIP() []byte {
	file_client_v1_client_proto_rawDescOnce.Do(func() {
		file_client_v1_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v1_client_proto_rawDesc), len(file_client_v1_client_proto_rawDesc)))
	})
	return file_client_v1_client_proto_rawDescData
}

var file_client_v1_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_v1_client_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_client_v1_client_proto_goTypes = []any{
	(ClientStatus)(0),                  // 0: client.v1.ClientStatus
	(*Client)(nil),                     // 1: client.v1.Client
	(*CreateClientRequest)(nil),        // 2: client.v1.CreateClientRequest
	(*CreateClientResponse)(nil),       // 3: client.v1.CreateClientResponse
	(*ListClientsRequest)(nil),         // 4: client.v1.ListClientsRequest
	(*ListClientsResponse)(nil),        // 5: client.v1.ListClientsResponse
	(*DeleteClientRequest)(nil),        // 6: client.v1.DeleteClientRequest
	(*DeleteClientResponse)(nil),       // 7: client.v1.DeleteClientResponse
	(*RotateClientSecretRequest)(nil),  // 8: client.v1.RotateClientSecretRequest
	(*RotateClientSecretResponse)(nil), // 9: client.v1.RotateClientSecretResponse
	(*UpdateRedirectUrisRequest)(nil),  // 10: client.v1.UpdateRedirectUrisRequest
	(*UpdateRedirectUrisResponse)(nil), // 11: client.v1.UpdateRedirectUrisResponse
	(*VerifyClientRequest)(nil),        // 12: client.v1.VerifyClientRequest
	(*VerifyClientResponse)(nil),       // 13: client.v1.VerifyClientResponse
	(*timestamppb.Timestamp)(nil),      // 14: google.protobuf.Timestamp
}
var file_client_v1_client_proto_depIdxs = []int32{
	14, // 0: client.v1.Client.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: client.v1.Client.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: client.v1.Client.status:type_name -> client.v1.ClientStatus
	1,  // 3: client.v1.CreateClientResponse.client:type_name -> client.v1.Client
	1,  // 4: client.v1.ListClientsResponse.clients:type_name -> client.v1.Client
	1,  // 5: client.v1.UpdateRedirectUrisResponse.client:type_name -> client.v1.Client
	2,  // 6: client.v1.ClientService.CreateClient:input_type -> client.v1.CreateClientRequest
	4,  // 7: client.v1.ClientService.ListClients:input_type -> client.v1.ListClientsRequest
	6,  // 8: client.v1.ClientService.DeleteClient:input_type -> client.v1.DeleteClientRequest
	8,  // 9: client.v1.ClientService.RotateClientSecret:input_type -> client.v1.RotateClientSecretRequest
	10, // 10: client.v1.ClientService.UpdateRedirectUris:input_type -> client.v1.UpdateRedirectUrisRequest
	12, // 11: client.v1.ClientService.VerifyClient:input_type -> client.v1.VerifyClientRequest
	3,  // 12: client.v1.ClientService.CreateClient:output_type -> client.v1.CreateClientResponse
	5,  // 13: client.v1.ClientService.ListClients:output_type -> client.v1.ListClientsResponse
	7,  // 14: client.v1.ClientService.DeleteClient:output_type -> client.v1.DeleteClientResponse
	9,  // 15: client.v1.ClientService.RotateClientSecret:output_type -> client.v1.RotateClientSecretResponse
	11, // 16: client.v1.ClientService.UpdateRedirectUris:output_type -> client.v1.UpdateRedirectUrisResponse
	13, // 17: client.v1.ClientService.VerifyClient:output_type -> client.v1.VerifyClientResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_client_v1_client_proto_init() }
func file_client_v1_client_proto_init() {
	if File_client_v1_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v1_client_proto_rawDesc), len(file_client_v1_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_v1_client_proto_goTypes,
		DependencyIndexes: file_client_v1_client_proto_depIdxs,
		EnumInfos:         file_client_v1_client_proto_enumTypes,
		MessageInfos:      file_client_v1_client_proto_msgTypes,
	}.Build()
	File_client_v1_client_proto = out.File
	file_client_v1_client_proto_goTypes = nil
	file_client_v1_client_proto_depIdxs = nil
}
